name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install NPM modules
      run: npm install
    - name: Replace the backend endpoint
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js
    - name: Start BackEnd
      run: npm run start-be &
    - name: Start FrontEnd
      run: npm run start-fe &
    - name: Install Browsers
      run: npx playwright install 
    - name: Execute UI tests
      run: npm run test:ui

  deploy-be:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
        - name: Checkpout the repository
          uses: actions/checkout@v3
        - name: Deploy BackEnd
          uses: johnbeynon/render-deploy-action@v0.0.8
          with:
            service-id: ${{ secrets.MY_RENDER_SERVICE_ID_BE }}
            api-key: ${{ secrets.MY_RENDER_API_KEY }}
            wait-for-success: true

  deploy-fe:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the repository
          uses: actions/checkout@v3
        - name: Deploy FrontEnd
          uses: johnbeynon/render-deploy-action@v0.0.8
          with:
            service-id: ${{ secrets.MY_RENDER_SERVICE_ID_FE }}
            api-key: ${{ secrets.MY_RENDER_API_KEY }}
            wait-for-success: true